/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#ebe8e2",
        "on-secondary-fixed-variant": "#5c4222",
        "on-primary-fixed": "#201a17",
        "surface-tint": "#655d59",
        "primary-fixed-dim": "#d0c4bf",
        "primary-fixed": "#ede0db",
        "tertiary-fixed": "#f2dfd7",
        "surface-dim": "#dcdad4",
        "inverse-surface": "#31312d",
        "tertiary-container": "#231915",
        background: "#fcf9f3",
        "on-secondary-fixed": "#2b1700",
        outline: "#7f7570",
        error: "#ba1a1a",
        "surface-container": "#f0eee8",
        "primary-container": "#201a17",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1c1c18",
        "on-tertiary-fixed": "#231915",
        "on-primary": "#ffffff",
        primary: "#000000",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f6f3ed",
        "error-container": "#ffdad6",
        "surface-variant": "#e5e2dc",
        "on-primary-fixed-variant": "#4d4541",
        "on-surface": "#1c1c18",
        "surface-container-highest": "#e5e2dc",
        "secondary-fixed": "#ffddb9",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#8c827d",
        "tertiary-fixed-dim": "#d5c3bc",
        "on-error-container": "#93000a",
        "on-secondary-container": "#795b3a",
        surface: "#fcf9f3",
        "surface-bright": "#fcf9f3",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f3f0ea",
        "on-surface-variant": "#4e4541",
        tertiary: "#000000",
        "on-tertiary-container": "#90817b",
        "outline-variant": "#d1c4be",
        "inverse-primary": "#d0c4bf",
        "secondary-container": "#fed6ac",
        secondary: "#765937",
        "on-tertiary-fixed-variant": "#51443f",
        "secondary-fixed-dim": "#e6c097",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      spacing: {
        "margin-desktop": "5rem",
        "space-lg": "1.5rem",
        "space-sm": "0.75rem",
        "gutter-mobile": "1rem",
        "space-4xl": "10rem",
        "space-xs": "0.5rem",
        "space-2xl": "4rem",
        "space-xl": "2.5rem",
        "gutter-desktop": "2rem",
        "space-xxs": "0.25rem",
        "margin-mobile": "1.5rem",
        "space-md": "1rem",
        "space-3xl": "6.5rem",
      },
      fontFamily: {
        "headline-lg": ["var(--font-playfair)", "serif"],
        "display-xl": ["var(--font-playfair)", "serif"],
        "title-editorial": ["var(--font-playfair)", "serif"],
        "body-sm": ["var(--font-jakarta)", "sans-serif"],
        "label-caps": ["var(--font-jakarta)", "sans-serif"],
        "headline-sm": ["var(--font-playfair)", "serif"],
        "headline-lg-mobile": ["var(--font-playfair)", "serif"],
        "body-md": ["var(--font-jakarta)", "sans-serif"],
        "body-lg": ["var(--font-jakarta)", "sans-serif"],
        "display-xl-mobile": ["var(--font-playfair)", "serif"],
        "label-sm": ["var(--font-jakarta)", "sans-serif"],
        "headline-md": ["var(--font-playfair)", "serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "title-editorial": ["20px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "26px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "30px", letterSpacing: "0.01em", fontWeight: "300" }],
        "display-xl-mobile": ["44px", { lineHeight: "50px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
